apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-nginx
  labels:
    app: app-nginx-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-nginx
  template:
    metadata:
      labels:
        app: app1-nginx
    spec:
      containers:
      - name: azurecontainerapp
        image: terraformaksacr.azurecr.io/azcontainerapp:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 5000
