apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: ClusterRoleBinding
metadata:
  name: cluster-rolebinding-sre
  namespace: default
subjects:
# You can specify more than one "subject"
# Mapping SRE AD Group ID for SRE's to gain access to AKS cluster
- kind: Group
  name: 2b59f902-709b-475c-940d-6d60499a6f02 # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: cluster-role-sre # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io