apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aks-developer-role
  namespace: app
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
    - jobs
    - cronjobs
    verbs: ["*"]
