apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aks-sre-full-access-role
  namespace: app
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources:
    - jobs
    - cronjobs
    verbs: ["*"]
      
