apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aks-developer-rolebinding
  namespace: app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aks-developer-role
subjects:
  - kind: Group
    namespace: app
    name: 58c23484-0265-48fd-9fa7-50ee7d46cfc1