apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aks-sre-access-rolebinding
  namespace: app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aks-sre-full-access-role
subjects:
  - kind: Group
    namespace: app
    name: 2b59f902-709b-475c-940d-6d60499a6f02